Fix errors logged to console when entering play mode.
Specifically this one:

```
ArgumentNullException: Value cannot be null.
Parameter name: e
UnityEngine.UIElements.UQueryExtensions.Q (UnityEngine.UIElements.VisualElement e, System.String name, System.String className) (at <7f21349c9161407ba80a85ddaed7fabb>:0)
CesiumForUnity.CesiumCreditSystemUI.OnEnable () (at Packages/com.cesium.unity/Runtime/CesiumCreditSystemUI.cs:54)
```

And this one:

```
MissingReferenceException: The object of type 'CesiumCreditSystem' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not destroy the object.
CesiumForUnity.CesiumCreditSystem.OnSceneUnloaded (UnityEngine.SceneManagement.Scene scene) (at Packages/com.cesium.unity/Runtime/CesiumCreditSystem.cs:333)
UnityEngine.SceneManagement.SceneManager.Internal_SceneUnloaded (UnityEngine.SceneManagement.Scene scene) (at <7b2a272e51214e2f91bbc4fb4f28eff8>:0)
```